---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: https://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# 2020.2.2
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: e16c9b484ce33cebe2c8095f315deb727d3b8f99
  tag: 202.7319.50

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK

exclude:
  - code_samples
