---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: https://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# 2020.3
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: 4b94ba01122752d7576eb9d69638b6e89d1671b7
  tag: 203.5981.155

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK

exclude:
  - code_samples
